Crims.UI.Web.Enroll/Controllers/ApprovalController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using Crims.Data.Contracts;
using Crims.Data.Models;
using Crims.UI.Web.Enroll.Helpers;
using Crims.UI.Web.Enroll.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using MySql.Data.MySqlClient;
using Repository.Pattern.UnitOfWork;

namespace Crims.UI.Web.Enroll.Controllers
{
    public class ApprovalController : Controller
    {
        private IApprovalService _approvalService;
        private ICustomDataService _customDataService;
        private ICustomListService _customListService;
        private ICustomFieldService _customFieldService;
        private ICustomListDataService _customListDataService;
        private ICustomGroupService _customGroupService;
        private ICustomFieldTypeService _customFieldTypeService;
        private IBaseDataService _baseDataService;
        private IUnitOfWorkAsync _unitOfWork;
        public ApprovalController()
        {
            if (!User.Identity.IsAuthenticated)
            {
                RedirectToAction("Login", "Account");
            }
        }

        public ApprovalController(ICustomFieldService customFieldService, ICustomListDataService customListDataService, ICustomGroupService customGroupService, IBaseDataService baseDataService, ICustomDataService customDataService, ICustomListService customListService, ICustomFieldTypeService customFieldTypeService, IProjectService projectService, IApprovalService approvalService, IUnitOfWorkAsync unitOfWork)
        {
            _approvalService = approvalService;
            _customDataService = customDataService;
            _customFieldTypeService = customFieldTypeService;
            _baseDataService = baseDataService;
            _customGroupService = customGroupService;
            _customListDataService = customListDataService;
            _customListService = customListService;
            _customFieldService = customFieldService;
            _unitOfWork = unitOfWork;
        }

        public Project GetProjectInSession()
        {
            try
            {
                var currentProject = Session["_currentProject"] as Project;
                if (string.IsNullOrEmpty(currentProject?.ProjectCode))
                {
                    return new Project();
                }
                return currentProject;
            }
            catch (Exception ex)
            {
                return new Project();
            }
        }
        public ActionResult Index()
        {
            var currentProject = GetProjectInSession();
            if (currentProject == null)
            {
                return View(new List<BaseDataViewModel>());
            }
            var userId = User.Identity.GetUserId();
            var registeredUsers = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>().Users.Where(e => e.Id == userId).Include("UserInfo").ToList();
            if (!registeredUsers.Any())
            {
                return View(new List<BaseDataViewModel>());
            }

            var enrolledBy = registeredUsers[0].UserInfo.Id;
            var approved = (int)EnumManager.ApprovalStatus.Approved;
            var baseDataList = new List<BaseDataViewModel>();

            var connStr = ConfigurationManager.ConnectionStrings["crimsDbEntities"].ConnectionString; ;
            var conn = new MySqlConnection(connStr);
            conn.Open();

            if (User.IsInRole("Admin") || User.IsInRole("Site_Administrator"))
            {
                var sql = $"SELECT t.*, o.* FROM basedatas t JOIN userprofiles o ON o.Id = t.CreatedBy WHERE t.ProjectCode ='{currentProject.ProjectCode}' AND t.ApprovalStatus = '{approved}'";

                var cmd = new MySqlCommand(sql, conn);
                using (var rdr = cmd.ExecuteReader())
                {
                    while (rdr.Read())
                    {
                        if (!rdr.HasRows) continue;
                        var dateRegistered = Convert.ToDateTime(rdr["EnrollmentDate"].ToString());
                        var enrollmentDateStr = dateRegistered.ToString("dd/MM/yyyy");
                        var newUser = new BaseDataViewModel
                        {
                            TableId = Convert.ToInt32(rdr["TableId"].ToString()),
                            EnrollmentId = rdr["EnrollmentId"].ToString(),
                            ProjectCode = rdr["ProjectCode"].ToString(),
                            ProjectSiteId = rdr["ProjectSiteId"].ToString(),
                            Surname = rdr["Surname"].ToString(),
                            Firstname = rdr["Firstname"].ToString(),
                            EnrollmentOfficer = rdr["FullName"] + " (" + rdr["PhoneNumber"] + ")",
                            MiddleName = rdr["MiddleName"].ToString(),
                            Gender = rdr["Gender"].ToString(),
                            Title = rdr["Title"].ToString(),
                            Email = rdr["Email"].ToString(),
                            EnrollmentDateStr = enrollmentDateStr,
                            MobileNumber = rdr["MobileNumber"].ToString(),
                            CuntryCode = rdr["CuntryCode"].ToString(),
                            ProjectPrimaryCode = rdr["ProjectPrimaryCode"].ToString(),
                            DOB = rdr["DOB"].ToString(),
                            BiometricStatus = "Completed",
                            ApprovalStatus = Convert.ToInt32(rdr["ApprovalStatus"].ToString()),
                            EnrollmentDate = dateRegistered,
                            ValidIdNumber = rdr["ValidIdNumber"].ToString()
                        };

                        baseDataList.Add(newUser);
                    }
                }
            }

            else
            {
                if (!User.IsInRole("Enrollee"))
                {
                    var sql2 = $"SELECT t.*, o.* FROM basedatas t JOIN userprofiles o ON o.Id = t.CreatedBy WHERE t.ProjectCode ='{currentProject.ProjectCode}' AND  t.ApprovalStatus = '{approved}' AND (t.CreatedBy = '{enrolledBy}' OR t.LastUpdatedby = '{enrolledBy}')";

                    var cmd2 = new MySqlCommand(sql2, conn);
                    using (var rdr = cmd2.ExecuteReader())
                    {
                        while (rdr.Read())
                        {
                            if (!rdr.HasRows) continue;
                            var dateRegistered = Convert.ToDateTime(rdr["EnrollmentDate"].ToString());
                            var enrollmentDateStr = dateRegistered.ToString("dd/MM/yyyy");
                            var newUser = new BaseDataViewModel
                            {
                                TableId = Convert.ToInt32(rdr["TableId"].ToString()),
                                EnrollmentId = rdr["EnrollmentId"].ToString(),
                                ProjectCode = rdr["ProjectCode"].ToString(),
                                ProjectSiteId = rdr["ProjectSiteId"].ToString(),
                                Surname = rdr["Surname"].ToString(),
                                Firstname = rdr["Firstname"].ToString(),
                                EnrollmentOfficer = rdr["FullName"] + " (" + rdr["PhoneNumber"] + ")",
                                MiddleName = rdr["MiddleName"].ToString(),
                                Gender = rdr["Gender"].ToString(),
                                Title = rdr["Title"].ToString(),
                                EnrollmentDateStr = enrollmentDateStr,
                                Email = rdr["Email"].ToString(),
                                MobileNumber = rdr["MobileNumber"].ToString(),
                                CuntryCode = rdr["CuntryCode"].ToString(),
                                ProjectPrimaryCode = rdr["ProjectPrimaryCode"].ToString(),
                                DOB = rdr["DOB"].ToString(),
                                BiometricStatus = "Completed",
                                ApprovalStatus = Convert.ToInt32(rdr["ApprovalStatus"].ToString()),
                                EnrollmentDate = dateRegistered,
                                ValidIdNumber = rdr["ValidIdNumber"].ToString()
                            };

                            baseDataList.Add(newUser);
                        }
                    }
                }
                else
                {
                    return Redirect("Enrollment");
                }
            }
        
            if (!baseDataList.Any())
            {
                return View(new List<BaseDataViewModel>());
            }

            baseDataList.ForEach(p =>
            { 
                var enumName = Enum.GetName(typeof(EnumManager.ApprovalStatus), p.ApprovalStatus);
                if (enumName != null)p.ApprovalStatusStr = enumName.Replace("_", " ");
            });

            return View(baseDataList);
        }

        [HttpPost]
        public ActionResult ProcessApproval(Approval approval)
        {
            var acResponse = new ActivityResponse();
            try
            {
                if (!User.Identity.IsAuthenticated)
                {
                    acResponse.Code = -1;
                    acResponse.Message = "Your session has timed out. Please log in to continue";
                    return Json(acResponse, JsonRequestBehavior.AllowGet);
                }
                var userId = User.Identity.GetUserId();
                var registeredUsers = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>().Users.Where(e => e.Id == userId).Include("UserInfo").ToList();
                if (!registeredUsers.Any())
                {
                    acResponse.Code = -1;

Crims.UI.Web.Enroll/Views/Shared/_Gen_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Chams Residency and Identity Management System</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/css-custom")
    @Styles.Render("~/Content/css-admin-custom")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/bower_components/uidgerator_bundle.js"></script>
    <style type="text/css">
        .select2-container {
            width: 100% !important;
        }
    </style>
</head>
<body class="skin-blue sidebar-mini">
<label id="baseUrl" style="display: none"></label>
<div>

    <header class="main-header">
        <!-- Logo -->
        <a href="" class="logo">
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>Chams | RIMS</b></span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">

            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    @{
                        if (User.Identity.IsAuthenticated)
                        {
                            <li class="dropdown user user-menu">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    @*<img src="@Url.Content("~/Images/crims-logo.png")" class="user-image" alt="User Image">*@
                                    <span class="hidden-xs" style="width: 200px;">@User.Identity.Name</span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="@Url.Action("UserProfile", "Account")">
                                            <i class="fa fa-user text-aqua"></i> Profile
                                        </a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Index", "Enrollment")">
                                            <i class="fa fa-certificate text-aqua"></i> Self Enrollment
                                        </a>
                                    </li>
                                    <li>
                                        <a onclick="logout()" style="cursor: pointer">
                                            <i class="fa fa-lock text-red"></i> Signout
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        }
                    }

                </ul>
            </div>
        </nav>
    </header>
    <!-- Content Wrapper. Contains page content -->
    <div class="" style="padding-right: 10px; padding-left: 10px;">
        @RenderBody()
    </div><!-- /.content-wrapper -->
    <footer class="main-footer text-primary" style="margin-left: 0">
        <div class="pull-right hidden-xs">
            <b>Version</b> 1.0.0
        </div>
        <strong>CRIMS - Copyright &copy; @DateTime.Now.Year<a href="#">. Chams Residency and Identity Management System</a>.</strong> All rights reserved.
    </footer>


    <!-- Add the sidebar's background. This div must be placed
    immediately after the control sidebar -->
    <div class="control-sidebar-bg"></div>
</div><!-- ./wrapper -->

<div class="angular-center-container angular-center-container-position">
    <div class="angular-centered showBusy">
        <img src="@Url.Content("~/Content/img/workingonit.gif")" id="loading"/>
    </div>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
@RenderSection("JavaScript", required: false)

<script type="text/javascript">
    var baseUrl = '@Url.Content("~")'.replace(/\/$/, '');
    var baseUrl = '@Url.Content("~")'.replace(/\/$/, '');
    $('baseUrl').html(baseUrl);
    window.baseUrl = baseUrl;

    window.showUiBusy = function() {
        $('.showBusy').fadeIn();
    }

    window.hideUiBusy = function() {
        $('.showBusy').fadeOut();
    }

    $(function() {
        $('.showBusy').fadeOut();
    });
    $(function() {
        $('.showBusy').fadeOut();
    });

    function logout() {
        $.ajax({
            type: "POST",
            url: baseUrl + '/Account/LogOff',
            contentType: "application/json",
            dataType: 'json',
            data: {},
            beforeSend: function() { window.showUiBusy(); },
            success: function(response) {
                window.hideUiBusy();

                if (response < 1) {
                    return;
                }

                window.location.href = baseUrl + "/Home";
            }
        });
    }

</script>
</body>
</html>

Crims.UI.Web.Enroll/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Chams Residency and Identity Management System</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/css-custom")
    @Styles.Render("~/Content/css-admin-custom")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/bower_components/uidgerator_bundle.js"></script>
    <style type="text/css">
      
        .actionCol {
            width: 50px;
        }

        #enrolleeTable {
            table-layout: fixed;
            width: 1250px;
        }
        .select2-container{width: 100% !important;}
        .dataTable{width: 100% !important;}
    </style>
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <label id="baseUrl" style="display: none"></label>
<div class="wrapper">

    <header class="main-header">
        <!-- Logo -->
        <a href="@Url.Action("Index", "Home")" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>RIMS</b></span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>Chams RIMS</b></span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only">View Menu</span>
            </a>

            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    @{
                        if (User.Identity.IsAuthenticated)
                        {
                            <li class="dropdown user user-menu">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <img src="@Url.Content("~/Images/crims-logo.png")" class="user-image" alt="User Image">
                                    <span class="hidden-xs" style="width: 200px;" id="loginName"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="@Url.Action("MyProfile", "Account")">
                                            <i class="fa fa-user text-aqua"></i> Profile
                                        </a>
                                    </li>
                                    <li>
                                        <a onclick="logout()" style="cursor: pointer">
                                            <i class="fa fa-lock text-red"></i> Signout
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        }
                    }
                </ul>
            </div>
        </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <div class="user-panel">
                <div class="pull-left image">
                    <img src="@Url.Content("~/Images/crims-logo.png")" class="img-responsive" alt="User Image">
                </div>
                <div class="pull-left info">
                    @*<p>Field Agent</p>*@
                </div>
            </div>
            @*<div id="rl" style="display: none">@Roles.GetRolesForUser(User.Identity.GetUserId())</div>*@
            <!-- /.search form -->
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu">
                <li class="active">
                    <a href="@Url.Action("Index", "Home")">
                        <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                    </a>
                </li>
                <li class="treeview">
                    <a href="@Url.Action("ProjectOptions", "Home")"><i class="fa fa-tasks"></i> <span>Choose a Project</span></a>
                </li>
                @{
                    if (User.IsInRole("Admin"))
                    {
                        <li class="treeview">
                            <a href="@Url.Action("AppSetting", "Home")"><i class="fa fa-cog"></i><span>Settings</span></a>
                        </li>
                    }
                }
                @{
                    if (User.IsInRole("Admin") || User.IsInRole("Site_Administrator"))
                    {
                        <li class="treeview">
                            <a href="@Url.Action("ApproveEnrollment", "BaseData")"><i class="fa fa-check-circle-o"></i> <span>Approve Enrollment</span></a>
                        </li>
                        <li class="treeview">
                            <a href="@Url.Action("DataImport", "BaseData")"><i class="fa   fa-clipboard"></i><span>Data Import</span></a>
                        </li>
                        <li class="treeview">
                            <a href="@Url.Action("NewLicense", "Home")"><i class="fa  fa-cloud-download"></i> <span>Install new License</span></a>
                        </li>
                    }
                }

                <li class="treeview">
                    <a href="@Url.Action("Index", "BaseData")"><i class="fa fa-pencil-square-o"></i> <span>Enrollments</span></a>
                </li>

                <li><a href="@Url.Action("Index", "Approval")"><i class="fa fa-thumb-tack"></i><span>Approvals</span> </a></li>
                <li class="treeview">
                    <a href="@Url.Action("Rejections", "BaseData")"><i class="fa fa-recycle"></i> <span>Rejections</span></a>
                </li>
                @*<li><a ><i class="fa fa-circle-o"></i>Reports</a></li>*@
                @{
                    if (User.IsInRole("Admin") || User.IsInRole("Site_Administrator"))
                    {
                        <li><a href="@Url.Action("Users", "Account")"><i class="fa fa-users"></i><span>Users</span></a></li>
                    }
                }
                @*<li>
                        <a href="#">
                            <i class="fa fa-th"></i> <span>Get Supports</span>
                        </a>
                    </li>*@
            </ul>
        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper" style="padding-right: 10px; padding-left: 10px;">
        <div class="row">
            <div class="navbar-header col-md-12">
                <div class="col-md-3"></div>
                <div class="col-md-9">
                    <h4>Current Project : <span style="color: #008000" id="currentProjectInSession"></span></h4>
                </div>
            </div>
        </div>
        <div class="row">
            @RenderBody()
        </div>
    </div><!-- /.content-wrapper -->
    <footer class="main-footer text-primary">
        <div class="pull-right hidden-xs">
            <b>Version</b> 1.0.0
        </div>
        <strong>CRIMS - Copyright &copy; 2016<a href="#">. Chams Residency and Identity Management System</a>.</strong> All rights reserved.
    </footer>


    <!-- Add the sidebar's background. This div must be placed
    immediately after the control sidebar -->
    <div class="control-sidebar-bg"></div>
</div><!-- ./wrapper -->

<div class="angular-center-container angular-center-container-position">
    <div class="angular-centered showBusy">
        <img src="@Url.Content("~/Content/img/workingonit.gif")" id="loading"/>
    </div>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
@RenderSection("JavaScript", required: false)

<script type="text/javascript">

    window.showUiBusy = function() {
        $('.showBusy').fadeIn();
    }

    window.hideUiBusy = function() {
        $('.showBusy').fadeOut();
    }

    $(function() {
        window.showUiBusy();
    });

    var baseUrl = '@Url.Content("~")'.replace(/\/$/, '');
    $('baseUrl').html(baseUrl);
    window.baseUrl = baseUrl;

    function getCallbackObj() {
        if (callbackObj) {
            document.callbackObj = callbackObj;
        }
    }

    $(document).ready(function ()
    {
        $('.sidebar-toggle').click();
        window.hideUiBusy();
        $.ajax({
            url: baseUrl + '/Home/GetCurrentSessionProject',
            contentType: "application/json",
            dataType: 'json',
            type: 'GET',
            beforeSend: function() {
                window.showUiBusy();
            },
            success: function(response) {
                window.hideUiBusy();
                if (!response || response.LoginName.length < 1) {
                    window.location.href = baseUrl + "/Account/Login";
                } else {
                    if (!response.Project || response.Project.ProjectCode.length < 1) {
                        alert('Please specify the Project to work on');
                        window.location.href = baseUrl + "/Home/ProjectOptions";
                    } else {
                        $('#loginName').html(response.LoginName);
                        $('#currentProjectInSession').html(response.Project.ProjectName +
                            " (" +
                            response.Project.ProjectCode +
                            ")");
                        if (typeof callbackObj != 'undefined' && typeof callbackObj != null) {
                            callbackObj.setCurrentSessionProject(JSON.stringify(response.Project));
                        }
                    }
                }

            }
        });
    });

    function logout() {
        $.ajax({
            type: "POST",
            url: baseUrl + '/Account/LogOff',
            contentType: "application/json",
            dataType: 'json',
            data: {},
            beforeSend: function() { window.showUiBusy(); },
            success: function(response) {
                window.hideUiBusy();

                if (response < 1) {
                    return;
                }

                if (typeof callbackObj != 'undefined' && typeof callbackObj != null) {
                    if (callbackObj !== null) {
                        callbackObj.logOut();
                    }
                }
                window.location.href = baseUrl + "/Home";
            }
        });
    }
</script>

</body>
</html>